version: "3.8" # Replace with the latest stable version

services:
  mongo:
    image: mongo:latest # Replace with desired tag
    restart: always
    ports:
      - "27017:27017" # Consider restricting access
    volumes:
      - mongo-data:/data/db
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}  # Replace with environment variable or secret
    # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}  # Replace with environment variable or secret

  mongo-express:
    image: mongo-express:latest # Replace with desired tag
    restart: always
    ports:
      - "8081:8081" # Consider restricting access
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}  # Replace with environment variable or secret
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}  # Replace with environment variable or secret
      # ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-data:
